name: deferrable
description: Defer cleanup operations to the `dispose` method
version: 1.0.0+2
homepage: https://github.com/jackdreilly/deferrable
repository: https://github.com/jackdreilly/deferrable

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic:
  flutter_test:
    sdk: flutter
